# Generated by Django 2.2.10 on 2020-03-04 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('user', 'date', 'shift')},
        ),
    ]
