# Generated by Django 2.2.10 on 2020-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200304_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
