# Generated by Django 2.2.10 on 2020-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200305_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, default='/media/empid/image.png', null=True, upload_to='empid'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='project',
            field=models.CharField(blank=True, choices=[('bench', 'Bench'), ('devops', 'Devops'), ('production', 'Production'), ('hr', 'HR'), ('lead', 'Leaders')], default='bench', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='project_exp',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='total_exp',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
