# Generated by Django 2.2.10 on 2020-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200305_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
